// <auto-generated />
namespace AssemblyLine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ProductionCycleForEachLine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductionCycleForEachLine));
        
        string IMigrationMetadata.Id
        {
            get { return "201504270212244_ProductionCycleForEachLine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
